//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCT_TimeSheetsApp.TimeSheetWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetAppWebService", ConfigurationName="TimeSheetWS.TimeSheetAppWebService_Port")]
    public interface TimeSheetAppWebService_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (InsertTimeSheetDetail_Result) of message InsertTimeSheetDetail_Result does not match the default value (InsertTimeSheetDetail)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetAppWebService:InsertTimeSheetDet" +
            "ail", ReplyAction="*")]
        MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail_Result InsertTimeSheetDetail(MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetAppWebService:InsertTimeSheetDet" +
            "ail", ReplyAction="*")]
        System.Threading.Tasks.Task<MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail_Result> InsertTimeSheetDetailAsync(MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTimeSheetDetail", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetAppWebService", IsWrapped=true)]
    public partial class InsertTimeSheetDetail {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetAppWebService", Order=0)]
        public string timeSheetHeaderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetAppWebService", Order=1)]
        public int timeSheetLineNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetAppWebService", Order=2)]
        public string timeSheetDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetAppWebService", Order=3)]
        public decimal quantity;
        
        public InsertTimeSheetDetail() {
        }
        
        public InsertTimeSheetDetail(string timeSheetHeaderNo, int timeSheetLineNo, string timeSheetDate, decimal quantity) {
            this.timeSheetHeaderNo = timeSheetHeaderNo;
            this.timeSheetLineNo = timeSheetLineNo;
            this.timeSheetDate = timeSheetDate;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertTimeSheetDetail_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetAppWebService", IsWrapped=true)]
    public partial class InsertTimeSheetDetail_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetAppWebService", Order=0)]
        public string return_value;
        
        public InsertTimeSheetDetail_Result() {
        }
        
        public InsertTimeSheetDetail_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TimeSheetAppWebService_PortChannel : MCT_TimeSheetsApp.TimeSheetWS.TimeSheetAppWebService_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeSheetAppWebService_PortClient : System.ServiceModel.ClientBase<MCT_TimeSheetsApp.TimeSheetWS.TimeSheetAppWebService_Port>, MCT_TimeSheetsApp.TimeSheetWS.TimeSheetAppWebService_Port {
        
        public TimeSheetAppWebService_PortClient() {
        }
        
        public TimeSheetAppWebService_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimeSheetAppWebService_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeSheetAppWebService_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeSheetAppWebService_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail_Result MCT_TimeSheetsApp.TimeSheetWS.TimeSheetAppWebService_Port.InsertTimeSheetDetail(MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail request) {
            return base.Channel.InsertTimeSheetDetail(request);
        }
        
        public string InsertTimeSheetDetail(string timeSheetHeaderNo, int timeSheetLineNo, string timeSheetDate, decimal quantity) {
            MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail inValue = new MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail();
            inValue.timeSheetHeaderNo = timeSheetHeaderNo;
            inValue.timeSheetLineNo = timeSheetLineNo;
            inValue.timeSheetDate = timeSheetDate;
            inValue.quantity = quantity;
            MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail_Result retVal = ((MCT_TimeSheetsApp.TimeSheetWS.TimeSheetAppWebService_Port)(this)).InsertTimeSheetDetail(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail_Result> MCT_TimeSheetsApp.TimeSheetWS.TimeSheetAppWebService_Port.InsertTimeSheetDetailAsync(MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail request) {
            return base.Channel.InsertTimeSheetDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail_Result> InsertTimeSheetDetailAsync(string timeSheetHeaderNo, int timeSheetLineNo, string timeSheetDate, decimal quantity) {
            MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail inValue = new MCT_TimeSheetsApp.TimeSheetWS.InsertTimeSheetDetail();
            inValue.timeSheetHeaderNo = timeSheetHeaderNo;
            inValue.timeSheetLineNo = timeSheetLineNo;
            inValue.timeSheetDate = timeSheetDate;
            inValue.quantity = quantity;
            return ((MCT_TimeSheetsApp.TimeSheetWS.TimeSheetAppWebService_Port)(this)).InsertTimeSheetDetailAsync(inValue);
        }
    }
}
