//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCT_Teknoloji_A_Ş__Job_Planning_Line_Ext
    {
        public byte[] timestamp { get; set; }
        public string Job_No_ { get; set; }
        public string Job_Task_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Phase_Code { get; set; }
        public decimal Total_Cost__ACY_ { get; set; }
        public decimal Total_Price__ACY_ { get; set; }
        public byte Tentative { get; set; }
        public byte Unknown_Date { get; set; }
        public System.DateTime Start_Time { get; set; }
        public decimal Consultant_Claim { get; set; }
        public decimal Invoice_Amount__ACY_ { get; set; }
        public decimal Invoiced_Amount__ACY_ { get; set; }
        public decimal Posted_Amount__ACY_ { get; set; }
        public decimal Remaining_Amount__ACY_ { get; set; }
        public string Job_Status { get; set; }
        public string Alliance { get; set; }
        public byte PO_Mail_Sent { get; set; }
        public string Resource_Alternative_1 { get; set; }
        public string Resource_Alternative_2 { get; set; }
        public string address { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedTime { get; set; }
        public string Calendar_Event_Id { get; set; }
        public byte Update_Calendar { get; set; }
        public string Calendar_Event_Id_Found { get; set; }
        public int Entry_No_ { get; set; }
        public byte Prepaid { get; set; }
        public byte EUR { get; set; }
        public decimal Consultant_Claim_Amount { get; set; }
        public string Training_Code { get; set; }
    }
}
