//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MCT_Entities : DbContext
    {
        public MCT_Entities()
            : base("name=MCT_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MCTSPWebLoginCredentials> MCTSPWebLoginCredentials { get; set; }
        public virtual DbSet<MCTTimeSheetAppSetup> MCTTimeSheetAppSetup { get; set; }
        public virtual DbSet<Resource> Resource { get; set; }
        public virtual DbSet<Time_Sheet_Header> Time_Sheet_Header { get; set; }
        public virtual DbSet<Time_Sheet_Line> Time_Sheet_Line { get; set; }
        public virtual DbSet<Salesperson_Purchaser> Salesperson_Purchaser { get; set; }
        public virtual DbSet<Time_Sheet_Detail> Time_Sheet_Detail { get; set; }
    }
}
