//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCT_Teknoloji_A_Ş__Resource_Ext
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string E_Mail { get; set; }
        public decimal Direct_Unit_Cost__ACY_ { get; set; }
        public decimal Unit_Cost__ACY_ { get; set; }
        public decimal Unit_Price__ACY_ { get; set; }
        public string Mobile_Phone_No_ { get; set; }
        public byte Account_Executive { get; set; }
        public byte Trainer { get; set; }
        public decimal Daily_Fee { get; set; }
        public decimal Annual_Cost__ACY_ { get; set; }
        public decimal Happy_Sheet_Average { get; set; }
        public decimal Net_Promoting_Score { get; set; }
        public decimal Happy_Sheet_Trainer { get; set; }
        public int Job_Type { get; set; }
        public decimal Monthly_Capacity { get; set; }
        public string Web_Username { get; set; }
        public string Web_Password { get; set; }
        public byte Timesheet_User { get; set; }
        public byte Dont_Work_on_Saturday { get; set; }
        public byte Dont_Work_on_Sunday { get; set; }
        public byte Dont_Work_on_Monday { get; set; }
        public byte Dont_Work_on_Tuesday { get; set; }
        public byte Dont_Work_on_Wednesday { get; set; }
        public byte Dont_Work_on_Thursday { get; set; }
        public byte Dont_Work_on_Friday { get; set; }
        public byte Update_Calendar { get; set; }
    }
}
