//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mct2016Entities : DbContext
    {
        public mct2016Entities()
            : base("name=mct2016Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MCT_Teknoloji_A_Ş__MCTSPWebLoginCredentials> MCT_Teknoloji_A_Ş__MCTSPWebLoginCredentials { get; set; }
        public virtual DbSet<MCT_Teknoloji_A_Ş__MCTTimeSheetAppSetup> MCT_Teknoloji_A_Ş__MCTTimeSheetAppSetup { get; set; }
        public virtual DbSet<MCT_Teknoloji_A_Ş__Resource_Ext> MCT_Teknoloji_A_Ş__Resource_Ext { get; set; }
        public virtual DbSet<MCT_Teknoloji_A_Ş__Resource> MCT_Teknoloji_A_Ş__Resource { get; set; }
        public virtual DbSet<MCT_Teknoloji_A_Ş__Salesperson_Purchaser> MCT_Teknoloji_A_Ş__Salesperson_Purchaser { get; set; }
        public virtual DbSet<MCT_Teknoloji_A_Ş__Time_Sheet_Detai> MCT_Teknoloji_A_Ş__Time_Sheet_Detail { get; set; }
        public virtual DbSet<MCT_Teknoloji_A_Ş__Time_Sheet_Header> MCT_Teknoloji_A_Ş__Time_Sheet_Header { get; set; }
        public virtual DbSet<MCT_Teknoloji_A_Ş__Time_Sheet_Line> MCT_Teknoloji_A_Ş__Time_Sheet_Line { get; set; }
        public virtual DbSet<MCT_Teknoloji_A_Ş__Job> MCT_Teknoloji_A_Ş__Job { get; set; }
        public virtual DbSet<MCT_Teknoloji_A_Ş__Job_Planning_Line_Ext> MCT_Teknoloji_A_Ş__Job_Planning_Line_Ext { get; set; }
        public virtual DbSet<MCT_Teknoloji_A_Ş__Job_Planning_Line> MCT_Teknoloji_A_Ş__Job_Planning_Line { get; set; }
        public virtual DbSet<MCT_Teknoloji_A_Ş__Job_Task> MCT_Teknoloji_A_Ş__Job_Task { get; set; }
        public virtual DbSet<MCT_Teknoloji_A_Ş__Work_Type> MCT_Teknoloji_A_Ş__Work_Type { get; set; }
    }
}
