//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCTSPWebLoginCredentials
    {
        public byte[] timestamp { get; set; }
        public string MCTSPLoginPrimaryKey { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public byte ChangePassword { get; set; }
        public string NoSeries { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public System.Guid C_systemId { get; set; }
        public string ResourceNo { get; set; }
    }
}
