//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCTTimeSheetAppSetup
    {
        public byte[] timestamp { get; set; }
        public string MCTTimeSheetAppPrimaryKey { get; set; }
        public string MCTTimeSheetAppLoginNos { get; set; }
        public string MCTTimeSheetAppAdminEmail { get; set; }
        public System.Guid C_systemId { get; set; }
    }
}
